_target_: src.models.opticalflow_module.OpticalFlowModule

weights: [1, 0.5, 0.25, 0.125, 0.125, 0.125]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.pwcnet.PWCNet
  search_range: 4
