_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.pwcnet.PWCNet
  search_range: 4
