_target_: src.models.optical_flow_module.OpticalFlowModule

weights: [1, 0.8, 0.6, 0.4, 0.2, 0.1]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.upflownet_lite.UPFlowNetLite
  encoder_chs: [3, 16, 32, 64, 96, 128]
  output_shrink_level: 2  # output size is 1/(1<<output_shrink_level) of the input size
  search_range: 2
  mid_feature_ch: 32
  flow_estimator_conv_chs: [64, 32, 16]
  flow_refiner_conv_chs: [32, 32, 32, 32, 32]
  normalize_before_cost_volume: true
  normalize_moments_across_channels: true
  normalize_moments_across_images: false  # False recommended for small batch case, though set True in UFlow and UPFlow
  apply_sgu_upsample: true