_target_: src.datamodules.autoflow_datamodule.AutoFlowDataModule

train_data_dir: ${paths.data_dir}/train
val_data_dir: ${paths.data_dir}
test_data_dir: ${paths.data_dir}
layer_num: 4
width: 384
height: 384
gaussian_blur_prob: 0.5
motion_blur_prob: 0.5
fog_prob: 0.05
batch_size: 8
num_workers: 4
pin_memory: true
